-- Для @GeneratedValue(strategy = GenerationType.IDENTITY)
/*
create table client
(
    id   bigserial not null primary key,
    name varchar(50)
);

 */

-- Для @GeneratedValue(strategy = GenerationType.SEQUENCE)
create sequence hibernate_sequence start with 1 increment by 1;

create table address_data_set
(
    id     bigint not null generated by default as identity primary key,
    street varchar(50)
);

create table client
(
    id   bigint not null generated by default as identity primary key,
    name varchar(50),
    address_id bigint
);

create table phone_data_set
(
    id        bigint not null generated by default as identity primary key,
    number    varchar(50),
    client_id bigint
);
